apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: store-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-app
  template:
    metadata:
      labels:
        app: store-app
    spec:
      containers:
      - name: store-app
        image: store-app:latest # Change to your image repo if pushing to a registry
        ports:
        - containerPort: 5000
        env:
        - name: DB_PATH
          value: /data/store.db
        volumeMounts:
        - name: store-data
          mountPath: /data
      volumes:
      - name: store-data
        persistentVolumeClaim:
          claimName: store-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  type: NodePort
  selector:
    app: store-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007 